import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Warm Editorial Community: messages feel like a quiet correspondence desk, with a readable thread and enough margin around every reply.
import { ArrowLeft, MoreHorizontal, Paperclip, Search, Send, Smile } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { conversations, messagesByConversation } from "../data/mockData";
import { Avatar } from "../components/Avatar";
export default function Messages() {
    const [activeId, setActiveId] = useState("c1");
    const [draft, setDraft] = useState("");
    const active = conversations.find((conversation) => conversation.id === activeId) ?? conversations[0];
    const messages = messagesByConversation[activeId] ?? [];
    const send = () => { if (!draft.trim())
        return; toast("Message sent", { description: `A note is on its way to ${active.name}.` }); setDraft(""); };
    return _jsx("main", { className: "page-grid single-page-grid messages-page", children: _jsxs("section", { className: "messages-panel", children: [_jsxs("div", { className: "page-intro messages-intro", children: [_jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "Correspondence" }), _jsx("h1", { children: "Messages" })] }), _jsx("button", { className: "primary-button small-button", onClick: () => toast("New message is coming soon"), children: _jsx("span", { children: "New note" }) })] }), _jsxs("div", { className: "messages-layout", children: [_jsxs("div", { className: "conversation-list", children: [_jsxs("div", { className: "inbox-search", children: [_jsx(Search, { size: 16 }), _jsx("input", { placeholder: "Search messages", "aria-label": "Search messages" })] }), conversations.map((conversation) => _jsxs("button", { className: `conversation-row ${activeId === conversation.id ? "is-active" : ""}`, onClick: () => setActiveId(conversation.id), children: [_jsx(Avatar, { src: conversation.avatar, initials: conversation.initials, alt: conversation.name, size: "md", online: conversation.online }), _jsxs("span", { className: "conversation-copy", children: [_jsx("strong", { children: conversation.name }), _jsx("small", { children: conversation.preview })] }), _jsxs("span", { className: "conversation-meta", children: [_jsx("time", { children: conversation.time }), conversation.unread > 0 && _jsx("b", { children: conversation.unread })] })] }, conversation.id))] }), _jsxs("div", { className: "thread-panel", children: [_jsxs("div", { className: "thread-header", children: [_jsx("button", { className: "mobile-back icon-button", onClick: () => toast("Choose another conversation from the list"), "aria-label": "Back to conversations", children: _jsx(ArrowLeft, { size: 17 }) }), _jsx(Avatar, { src: active.avatar, initials: active.initials, alt: active.name, size: "sm", online: active.online }), _jsxs("div", { children: [_jsx("strong", { children: active.name }), _jsx("span", { children: active.online ? "Online now" : `@${active.handle}` })] }), _jsx("button", { className: "icon-button thread-more", "aria-label": "More options", onClick: () => toast("Conversation options are coming soon"), children: _jsx(MoreHorizontal, { size: 18 }) })] }), _jsxs("div", { className: "thread-body", children: [_jsx("div", { className: "thread-date", children: "Today" }), messages.map((message) => _jsxs("div", { className: `message-bubble ${message.from === "me" ? "from-me" : "from-them"}`, children: [_jsx("p", { children: message.text }), _jsx("time", { children: message.time })] }, message.id))] }), _jsxs("div", { className: "reply-area", children: [_jsxs("div", { className: "reply-input", children: [_jsx("input", { value: draft, onChange: (event) => setDraft(event.target.value), onKeyDown: (event) => { if (event.key === "Enter")
                                                        send(); }, placeholder: "Write a reply...", "aria-label": "Write a reply" }), _jsx("button", { onClick: () => toast("Attachments are coming soon"), "aria-label": "Attach a file", children: _jsx(Paperclip, { size: 17 }) }), _jsx("button", { onClick: () => toast("Reactions are coming soon"), "aria-label": "Add a reaction", children: _jsx(Smile, { size: 17 }) })] }), _jsx("button", { className: "send-button", onClick: send, "aria-label": "Send message", children: _jsx(Send, { size: 16 }) })] })] })] })] }) });
}
