import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Warm Editorial Community: the profile reads like a personal title page—strong identity, measured stats, and a simple archive of notes.
import { Grid2X2, Link as LinkIcon, MapPin, Pencil, Bookmark, MoreHorizontal } from "lucide-react";
import { toast } from "sonner";
import { Avatar } from "../components/Avatar";
import { PostCard } from "../components/PostCard";
import { currentUser } from "../data/mockData";
import { useApp } from "../context/AppContext";
export default function Profile() {
    const { posts } = useApp();
    const ownPosts = posts.filter((post) => post.author.handle === currentUser.handle);
    return _jsx("main", { className: "page-grid single-page-grid", children: _jsxs("section", { className: "profile-page", children: [_jsxs("div", { className: "profile-cover", children: [_jsx("div", { className: "cover-shape cover-shape-one" }), _jsx("div", { className: "cover-shape cover-shape-two" }), _jsx("button", { className: "cover-menu icon-button", onClick: () => toast("Profile options are coming soon"), "aria-label": "Profile options", children: _jsx(MoreHorizontal, { size: 19 }) })] }), _jsxs("div", { className: "profile-heading", children: [_jsx(Avatar, { src: currentUser.avatar, initials: currentUser.initials, alt: currentUser.name, size: "xl", ring: true }), _jsx("div", { className: "profile-actions", children: _jsxs("button", { className: "secondary-button", onClick: () => toast("Profile editing is coming soon"), children: [_jsx(Pencil, { size: 15 }), " Edit profile"] }) })] }), _jsxs("div", { className: "profile-copy", children: [_jsxs("span", { className: "eyebrow", children: ["@", currentUser.handle] }), _jsx("h1", { children: currentUser.name }), _jsxs("p", { children: [currentUser.role, ". Collecting the ordinary, one note at a time."] }), _jsxs("div", { className: "profile-details", children: [_jsxs("span", { children: [_jsx(MapPin, { size: 14 }), currentUser.location] }), _jsxs("span", { children: [_jsx(LinkIcon, { size: 14 }), "commonplace.journal"] }), _jsx("span", { children: "Joined March 2023" })] })] }), _jsxs("div", { className: "profile-stats", children: [_jsxs("div", { children: [_jsx("strong", { children: currentUser.following }), _jsx("span", { children: "Following" })] }), _jsxs("div", { children: [_jsx("strong", { children: currentUser.followers.toLocaleString() }), _jsx("span", { children: "Followers" })] }), _jsxs("div", { children: [_jsx("strong", { children: ownPosts.length }), _jsx("span", { children: "Notes" })] })] }), _jsxs("div", { className: "profile-tabs", children: [_jsxs("button", { className: "profile-tab is-active", children: [_jsx(Grid2X2, { size: 16 }), " Notes"] }), _jsxs("button", { className: "profile-tab", onClick: () => toast("Saved notes are coming soon"), children: [_jsx(Bookmark, { size: 16 }), " Saved"] })] }), _jsx("div", { className: "profile-posts", children: ownPosts.length ? ownPosts.map((post) => _jsx(PostCard, { post: post }, post.id)) : _jsxs("div", { className: "empty-note", children: [_jsx("p", { children: "No notes yet." }), _jsx("span", { children: "Share a small wonder to begin your archive." })] }) })] }) });
}
