// Dinoc India Edition: settings are a practical control room for identity, privacy, notifications, and the way the city looks at night.

import { Bell, ChevronRight, Eye, LockKeyhole, Moon, Palette, ShieldCheck, Sun, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useTheme } from "../context/ThemeContext";

const accountItems = [{ label: "Profile information", description: "Name, handle, and photo", icon: UserRound }, { label: "Password & security", description: "Keep your account safe", icon: ShieldCheck }];

export default function Settings() {
  const [privateAccount, setPrivateAccount] = useState(false);
  const [emailNotes, setEmailNotes] = useState(true);
  const [quietMode, setQuietMode] = useState(false);
  const { theme, toggleTheme } = useTheme();
  return <main className="page-grid single-page-grid"><section className="narrow-page settings-page"><div className="page-intro"><div><span className="eyebrow">Make it yours · Dinoc</span><h1>Settings</h1><p className="page-subtitle">Tune your corner of the community without losing the good stuff.</p></div></div><div className="settings-card"><div className="settings-group"><span className="eyebrow">Account</span>{accountItems.map(({ label, description, icon: Icon }) => <button className="settings-row" key={label} onClick={() => toast(`${label} opened`, { description: "This local demo is ready for a connected account flow." })}><span className="settings-icon"><Icon size={17} /></span><span><strong>{label}</strong><small>{description}</small></span><ChevronRight size={17} /></button>)}</div><div className="settings-divider" /><div className="settings-group"><span className="eyebrow">Preferences</span><div className="settings-row"><span className="settings-icon"><Bell size={17} /></span><span><strong>Notifications</strong><small>{emailNotes ? "You will hear about replies and follows" : "Only important account updates"}</small></span><button className={`toggle ${emailNotes ? "is-on" : ""}`} onClick={() => setEmailNotes((value) => !value)} aria-label="Toggle notification emails"><span /></button></div><div className="settings-row"><span className="settings-icon"><LockKeyhole size={17} /></span><span><strong>Private account</strong><small>{privateAccount ? "Only approved people see your notes" : "Your notes are open to the community"}</small></span><button className={`toggle ${privateAccount ? "is-on" : ""}`} onClick={() => setPrivateAccount((value) => !value)} aria-label="Toggle private account"><span /></button></div><div className="settings-row"><span className="settings-icon"><Moon size={17} /></span><span><strong>Quiet mode</strong><small>{quietMode ? "Reduced motion and fewer nudges" : "Normal movement and updates"}</small></span><button className={`toggle ${quietMode ? "is-on" : ""}`} onClick={() => setQuietMode((value) => !value)} aria-label="Toggle quiet mode"><span /></button></div><div className="settings-row"><span className="settings-icon">{theme === "day" ? <Sun size={17} /> : <Palette size={17} />}</span><span><strong>{theme === "day" ? "Day mode" : "Night mode"}</strong><small>Switch the colour of your Dinoc corner</small></span><button className={`toggle ${theme === "night" ? "is-on" : ""}`} onClick={toggleTheme} aria-label="Toggle day and night mode"><span /></button></div></div></div><div className="settings-footnote"><Eye size={16} /><p>Your choices are saved on this device for now.</p></div></section></main>;
}
