import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Warm Editorial Community: settings are presented like a considered preferences sheet, with plain language and soft, non-alarming controls.
import { Bell, ChevronRight, Eye, LockKeyhole, Moon, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
const settingGroups = [
    { title: "Your account", items: [{ label: "Profile information", description: "Name, handle, and photo", icon: UserRound }, { label: "Password & security", description: "Keep your account safe", icon: ShieldCheck }] },
    { title: "Your space", items: [{ label: "Notifications", description: "Choose what reaches you", icon: Bell }, { label: "Privacy", description: "Control who sees your notes", icon: LockKeyhole }, { label: "Appearance", description: "Light, warm, and easy on the eyes", icon: Moon }] },
];
export default function Settings() {
    const [privateAccount, setPrivateAccount] = useState(false);
    const [emailNotes, setEmailNotes] = useState(true);
    return _jsx("main", { className: "page-grid single-page-grid", children: _jsxs("section", { className: "narrow-page settings-page", children: [_jsx("div", { className: "page-intro", children: _jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "Make it yours" }), _jsx("h1", { children: "Settings" })] }) }), _jsxs("div", { className: "settings-card", children: [_jsxs("div", { className: "settings-group", children: [_jsx("span", { className: "eyebrow", children: "Account" }), settingGroups[0].items.map(({ label, description, icon: Icon }) => _jsxs("button", { className: "settings-row", onClick: () => toast(`${label} is coming soon`, { description }), children: [_jsx("span", { className: "settings-icon", children: _jsx(Icon, { size: 17 }) }), _jsxs("span", { children: [_jsx("strong", { children: label }), _jsx("small", { children: description })] }), _jsx(ChevronRight, { size: 17 })] }, label))] }), _jsx("div", { className: "settings-divider" }), _jsxs("div", { className: "settings-group", children: [_jsx("span", { className: "eyebrow", children: "Preferences" }), settingGroups[1].items.map(({ label, description, icon: Icon }) => _jsxs("div", { className: "settings-row", children: [_jsx("span", { className: "settings-icon", children: _jsx(Icon, { size: 17 }) }), _jsxs("span", { children: [_jsx("strong", { children: label }), _jsx("small", { children: description })] }), label === "Privacy" ? _jsx("button", { className: `toggle ${privateAccount ? "is-on" : ""}`, onClick: () => setPrivateAccount((value) => !value), "aria-label": "Toggle private account", children: _jsx("span", {}) }) : label === "Notifications" ? _jsx("button", { className: `toggle ${emailNotes ? "is-on" : ""}`, onClick: () => setEmailNotes((value) => !value), "aria-label": "Toggle notification emails", children: _jsx("span", {}) }) : _jsx(ChevronRight, { size: 17 })] }, label))] })] }), _jsxs("div", { className: "settings-footnote", children: [_jsx(Eye, { size: 16 }), _jsx("p", { children: "Your choices are saved on this device for now." })] })] }) });
}
