// Dinoc India Edition: every post is a social object with clear reactions, local context, and an expressive visual rhythm.

import { Bookmark, Heart, MessageCircle, MoreHorizontal, Send, Share2 } from "lucide-react";
import { toast } from "sonner";
import { usePosts } from "../context/PostContext";
import { Avatar } from "./Navbar";

const fallbackImage = "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=80";

export default function PostCard({ post, onOpenComments }) {
  const { toggleLike, toggleSave, sharePost } = usePosts();
  const kind = post.kind || (post.id === "p1" ? "quote" : post.image ? "photo" : "note");
  const postClass = `post-card post-${kind}`;
  const share = () => { sharePost(post.id); toast("Post shared", { description: "It is ready to send to your people." }); };
  return <article className={postClass}><div className="post-header"><Avatar src={post.author.avatar} initials={post.author.initials} alt={post.author.name} size="md" /><div className="post-byline"><strong>{post.author.name}</strong><span>@{post.author.handle} <i>·</i> {post.time}</span></div><button className="icon-button more-button" aria-label={`More options for ${post.author.name}`} onClick={() => toast("Post options", { description: "Mute, report, and save controls are coming next." })}><MoreHorizontal size={18} /></button></div>{kind === "quote" && <div className="quote-mark" aria-hidden="true">“</div>}<p className="post-copy">{post.text}</p>{post.image && <figure className="post-figure"><img className="post-image" src={post.image} alt={`${post.author.name}'s post from ${post.location}`} onError={(event) => { event.currentTarget.src = fallbackImage; }} /><figcaption><span>{kind === "photo" ? "A moment from" : "Shared thought from"} {post.location}</span><span>#{post.tags[0]}</span></figcaption></figure>}{!post.image && <div className="note-caption"><span>From the journal · {post.location}</span><span>#{post.tags[0]}</span></div>}<div className="post-location"><span className="location-pin">⌖</span>{post.location}<span className="post-tag">#{post.tags[1] || post.tags[0]}</span></div><div className="post-actions"><div className="post-action-group"><button className={`post-action ${post.liked ? "is-liked" : ""}`} onClick={() => toggleLike(post.id)} aria-label={post.liked ? "Unlike post" : "Like post"}><Heart size={18} fill={post.liked ? "currentColor" : "none"} /><span>{post.likes}</span></button><button className="post-action" onClick={() => onOpenComments ? onOpenComments(post) : toast("Comments are ready", { description: "Open the comments panel to join in." })} aria-label="View comments"><MessageCircle size={18} /><span>{post.comments}</span></button><button className="post-action" onClick={share} aria-label="Share post"><Share2 size={17} /><span>{post.shares}</span></button><button className="post-action" onClick={() => toast("Send to a friend", { description: "Choose a chat from Messages to share this post." })} aria-label="Send post"><Send size={16} /></button></div><button className={`save-button ${post.saved ? "is-saved" : ""}`} onClick={() => toggleSave(post.id)} aria-label={post.saved ? "Remove from saved" : "Save post"}><Bookmark size={18} fill={post.saved ? "currentColor" : "none"} /></button></div></article>;
}
