// Warm Editorial Community: the contextual rail is a paper margin—small prompts and people to notice, never a noisy recommendation engine.

import { ArrowUpRight, Check, Plus } from "lucide-react";
import { toast } from "sonner";
import { peopleToFollow, trendingTopics } from "../data/mockData";
import { usePosts } from "../context/PostContext";
import { Avatar } from "./Navbar";

export default function RightSidebar() {
  const { following, followUser } = usePosts();
  return <aside className="right-rail"><section className="prompt-note"><span className="eyebrow">A question for today</span><h2>What deserves a second look?</h2><p>Leave a little room for the detail you almost walked past.</p><button onClick={() => toast("Prompt saved", { description: "You can return to it whenever you like." })}>Keep this prompt <ArrowUpRight size={15} /></button></section><section className="rail-section"><div className="section-heading"><div><span className="eyebrow">The current page</span><h2>Trending quietly</h2></div><button className="icon-button" onClick={() => toast("Trends refreshed")} aria-label="Refresh trends">↻</button></div><div className="trend-list">{trendingTopics.map((topic, index) => <button className="trend-row" key={topic.label} onClick={() => toast(`Opening #${topic.label}`, { description: topic.count })}><span className="trend-number">0{index + 1}</span><span><strong>#{topic.label}</strong><small>{topic.count}</small></span><ArrowUpRight size={15} /></button>)}</div></section><section className="rail-section"><div className="section-heading"><div><span className="eyebrow">Good company</span><h2>People to follow</h2></div><button className="quiet-link" onClick={() => toast("More people are coming soon")}>More</button></div><div className="people-list">{peopleToFollow.map((person) => { const isFollowing = following.includes(person.id); return <div className="person-row" key={person.id}><Avatar src={person.avatar} initials={person.initials} alt={person.name} size="sm" /><div className="person-copy"><strong>{person.name}</strong><span>@{person.handle}</span><small>{person.role}</small></div><button className={`follow-button ${isFollowing ? "is-following" : ""}`} onClick={() => { followUser(person.id); toast(isFollowing ? `Unfollowed ${person.name}` : `Following ${person.name}`); }} aria-label={`${isFollowing ? "Unfollow" : "Follow"} ${person.name}`}>{isFollowing ? <Check size={15} /> : <Plus size={15} />}</button></div>; })}</div></section><div className="rail-meta"><span>Dinoc social · 2026</span><button onClick={() => toast("About is coming soon")}>About</button><button onClick={() => toast("Guidelines are coming soon")}>Guidelines</button></div></aside>;
}
