import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// Warm Editorial Community: the contextual rail is a paper margin—small prompts and people to notice, never a noisy recommendation engine.
import { ArrowUpRight, Check, Plus } from "lucide-react";
import { toast } from "sonner";
import { peopleToFollow, trendingTopics } from "../data/mockData";
import { useApp } from "../context/AppContext";
import { Avatar } from "./Avatar";
export function RightRail() {
    const { following, followUser } = useApp();
    return _jsxs("aside", { className: "right-rail", children: [_jsxs("section", { className: "prompt-note", children: [_jsx("span", { className: "eyebrow", children: "A question for today" }), _jsx("h2", { children: "What deserves a second look?" }), _jsx("p", { children: "Leave a little room for the detail you almost walked past." }), _jsxs("button", { onClick: () => toast("Prompt saved", { description: "You can return to it whenever you like." }), children: ["Keep this prompt ", _jsx(ArrowUpRight, { size: 15 })] })] }), _jsxs("section", { className: "rail-section", children: [_jsxs("div", { className: "section-heading", children: [_jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "The current page" }), _jsx("h2", { children: "Trending quietly" })] }), _jsx("button", { className: "icon-button", onClick: () => toast("Trends refreshed"), "aria-label": "Refresh trends", children: "\u21BB" })] }), _jsx("div", { className: "trend-list", children: trendingTopics.map((topic, index) => _jsxs("button", { className: "trend-row", onClick: () => toast(`Opening #${topic.label}`, { description: topic.count }), children: [_jsxs("span", { className: "trend-number", children: ["0", index + 1] }), _jsxs("span", { children: [_jsxs("strong", { children: ["#", topic.label] }), _jsx("small", { children: topic.count })] }), _jsx(ArrowUpRight, { size: 15 })] }, topic.label)) })] }), _jsxs("section", { className: "rail-section", children: [_jsxs("div", { className: "section-heading", children: [_jsxs("div", { children: [_jsx("span", { className: "eyebrow", children: "Good company" }), _jsx("h2", { children: "People to follow" })] }), _jsx("button", { className: "quiet-link", onClick: () => toast("More people are coming soon"), children: "More" })] }), _jsx("div", { className: "people-list", children: peopleToFollow.map((person) => { const isFollowing = following.includes(person.id); return _jsxs("div", { className: "person-row", children: [_jsx(Avatar, { src: person.avatar, initials: person.initials, alt: person.name, size: "sm" }), _jsxs("div", { className: "person-copy", children: [_jsx("strong", { children: person.name }), _jsxs("span", { children: ["@", person.handle] }), _jsx("small", { children: person.role })] }), _jsx("button", { className: `follow-button ${isFollowing ? "is-following" : ""}`, onClick: () => { followUser(person.id); toast(isFollowing ? `Unfollowed ${person.name}` : `Following ${person.name}`); }, "aria-label": `${isFollowing ? "Unfollow" : "Follow"} ${person.name}`, children: isFollowing ? _jsx(Check, { size: 15 }) : _jsx(Plus, { size: 15 }) })] }, person.id); }) })] }), _jsxs("div", { className: "rail-meta", children: [_jsx("span", { children: "Commonplace journal \u00B7 2026" }), _jsx("button", { onClick: () => toast("About is coming soon"), children: "About" }), _jsx("button", { onClick: () => toast("Guidelines are coming soon"), children: "Guidelines" })] })] });
}
